# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-27 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_stuser_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuser',
            name='city',
        ),
    ]
