# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-27 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_stuser_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuser',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
