# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-30 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20161228_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuser',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
